name: Manual Build and Package on Windows

on:
  workflow_dispatch:
    inputs:
     logLevel:
       description: 'Log level'
       required: true
       default: 'warning'

jobs:
  build-and-package:
    runs-on: windows-latest  # 使用最新的Windows虚拟环境
    steps:
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.9.0'  # 使用最新版本的Node.js
    - name: Install Yarn
      run: npm install -g yarn  # 全局安装Yarn
    - name: Install dependencies
      run:  cd ${{ github.workspace }}; git clone https://github.com/X-ChenD-Hai/flipper.git;cd ./flipper/desktop;yarn  # 安装项目依赖
    # 指定在项目的desktop目录下运行
    - name: Build for Windows
      run: cd ${{ github.workspace }}\flipper\desktop;yarn build --win  # 构建项目
      # 使用GitHub提供的workspace变量

    - name: Terminate Processes
      run: |
        # 指定要解除进程的目录路径
        $directoryPath = "D:\a\flipper\flipper\flipper\dist\flipper-server-windows"

        # 获取该目录下所有进程，并递归子目录
        $processes = Get-Process | Where-Object { $_.MainModule.FileName -like "*$directoryPath*" }

        # 终止这些进程
        foreach ($process in $processes) {
            Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
        }
      shell: pwsh


    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: desktop-package
        path: ${{ github.workspace }}\flipper\dist  # 指定压缩文件的路径
