name: Test Env

on:
  workflow_dispatch:
    inputs:
     logLevel:
       description: 'Log level'
       required: true
       default: 'warning'

jobs:
  build-and-package:
    runs-on: windows-latest  # 使用最新的Windows虚拟环境
    steps:
    
     - name: ls
       run: cd  ${{ github.workspace }};git clone https://github.com/X-ChenD-Hai/flipper.git;cd flipper;echo(ls)
     - name: pwd
       run: echo (pwd)
